name: ci

on:
  push:
    paths-ignore:
      - '*.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12, 14, 16, 18]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm install
      - name: Run Tests
        run: npm run test:parallel

  test-ts-types:
    needs:
      - test
    runs-on: ubuntu-latest
    name: Typescript Types
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: npm install

      - name: Typings
        run: npm run test:tsd

  coverage:
    needs:
      - test-ts-types
    runs-on: ubuntu-latest
    name: coverage

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          always-auth: false
          node-version: 16

      - name: Run npm install
        run: npm install

      - name: Run Tests
        run: npm run test:coverage

      - name: Generate LCOV
        run: npm run coveralls

      - name: Update Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if: success()

  automerge:
    needs:
      - coverage
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}